name: React Build & Deploy to S3

on:
  push:
    branches:
      - master  # Your main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 4️⃣ Build project
      - name: Build project
        run: npm run build

      # 5️⃣ Configure AWS credentials
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # 6️⃣ Deploy build folder to S3
      - name: Deploy to S3
        run: aws s3 sync build/ s3://myself-emaan-bucket --delete 

      # 7️⃣ Invalidate CloudFront cache
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E1Y0AGZN4LJQXZ \
            --paths "/*"
